### ISSUE TITLE
Bugs with layers and layer navigation

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#42]
1) Parameters are not sent from already existing devices in a layer.
      * Create a device layer
      * Add some devices
      * Save it
      * Close Bitwig
      * Reopen and load
      * Now navigate into the layer and select the device (can be tested with the Push script)
      * The selected device does not send any parameter information, except Direct Parameters are working fine
    
2) layerBank.addCanScrollChannelsUpObserver and layerBank.addCanScrollChannelsDownObserver
    always send false
    
3) layer.addVuMeterObserver stops firing after selectInMixer() and then selectParent() is called

4) getSend of a layer always returns null

    this.cursorDevice = host.createEditorCursorDevice (); 
    this.layerBank = this.cursorDevice.createLayerBank (this.numDeviceLayers); 
    layer = this.layerBank.getChannel (i); 
    var s = layer.getSend (j);
    s == null

**Comment by vosc** [comment]
1) Bitwig bug ID: FLOAT-7946; fixed in 1.1.6 (not online yet).

**Comment by git-moss** [comment]
Yeah!

**Comment by vosc** [comment]
5)
hasLayers for plugins - Bitwig Bug ID: FLOAT-7945, fixed in 1.1.6
sibling device bank - Bitwig Bug ID: FLOAT-7671, added in 1.1.6

**Comment by vosc** [comment]
2) Bitwig Issue ID: FLOAT-7949, fixed in 1.1.6

**Comment by git-moss** [comment]
1) works fine now
2) Did not understand your explanation but will rewrite to Drum API.
3) Not fixed yet, I moved this to a new Issue for easier tracking and added a description to reproduce it: https://github.com/teotigraphix/Framework4Bitwig/issues/53
4) Also moved to a separate Issue: https://github.com/teotigraphix/Framework4Bitwig/issues/54
5) Now broken for Bitwig Plugins, see https://github.com/teotigraphix/Framework4Bitwig/issues/52
New Sibling API works fine!

Will close this Issue now because it got quite confusing. Remaining Issues are moved to new entries.

**Comment by git-moss** [comment]
Also see https://github.com/teotigraphix/Framework4Bitwig/issues/55 for problems with sibling bank.
